server:
  port: 8080

spring:
  application:
    name: demo-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  queue:
    name: demo-queue
  exchange:
    name: demo-exchange
  routing-key: demo-routing-key