server:
  port: 8080

spring:
  application:
    name: demo-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

rabbitmq:
  queue-1:
    name: demo-queue
  queue-2:
    name: demo-json-queue
  exchange:
    name: demo-exchange
  routing-1:
    key: demo-routing-key
  routing-2:
    key: demo-json-routing-key